services:
  mysql:
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: personas_user
      MYSQL_PASSWORD: personas_pass
      MYSQL_ROOT_PASSWORD: root1234

  personas-app:
    ports:
      - "8080:8080"
    environment:
      DB_USER: personas_user
      DB_PASSWORD: personas_pass