services:
  mysql:
    container_name: personas-mysql-dev
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: personasdb
      MYSQL_USER: personas_user
      MYSQL_PASSWORD: personas_pass
      MYSQL_ROOT_PASSWORD: root1234
    volumes:
      - mysql_dev_data:/var/lib/mysql

  personas-app:
    container_name: personas-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_URL: jdbc:mysql://mysql:3306/personasdb
      DB_USER: personas_user
      DB_PASSWORD: personas_pass

volumes:
  mysql_dev_data: