name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Give execute permission to mvnw
        working-directory: Personas
        run: chmod +x mvnw

      - name: Build & test with Maven
        working-directory: Personas
        run: ./mvnw clean test -Dspring.profiles.active=test

      - name: Build Docker images (prod)
        working-directory: Personas
        run: docker compose --env-file .env.prod -f Personas/docker-compose.prod.yml build

      - name: Up containers (prod)
        working-directory: Personas
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          DB_USER: ${{ secrets.MYSQL_USER }}
          DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: docker compose -f docker-compose.prod.yml up -d

      - name: Wait for application
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8080/actuator/health | grep UP; then
              echo "App is UP"
              exit 0
            fi
            echo "Waiting for app..."
            sleep 5
          done
          echo "App did not start"
          exit 1

      - name: Stop containers
        if: always()
        working-directory: Personas
        run: docker compose -f docker-compose.prod.yml down -v